# Numpy

In [1]:
import numpy as np

In [2]:
!pip install numpy

In [4]:
#Creation of 1D array
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [9]:
print(arr.dtype)

int32


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [14]:
arr2 = np.array({10,20,30,40})
print(arr2)

{40, 10, 20, 30}


In [15]:
print(arr2.dtype)

object


In [16]:
print(type(arr2))

<class 'numpy.ndarray'>


In [17]:
arr.ndim

1

In [18]:
two_arr = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(two_arr)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


# Creation of different types of arrays

In [3]:
import numpy as np
ar_num = np.array([1, 2, 3, 4], dtype="float")
print(ar_num)

[1. 2. 3. 4.]


In [4]:
ar_com = np.array([1, 2, 3, 4], dtype="complex")

In [5]:
print(ar_com)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [8]:
# creating array with the help of arrange method
i=1
for i in range(1, 11):
    print(2*i)


2
4
6
8
10
12
14
16
18
20


In [12]:
table = np.arange(1,11)
print(table)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
x = np.arange(2,21,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
# with reshape
np.arange(31,52,3)

array([31, 34, 37, 40, 43, 46, 49])

In [18]:
np.arange(31,52,3).reshape(7,1)

array([[31],
       [34],
       [37],
       [40],
       [43],
       [46],
       [49]])

In [19]:
np.arange(31,52,3).reshape(1,7)

array([[31, 34, 37, 40, 43, 46, 49]])

In [20]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [21]:
# possible combination for 2-D
np.arange(1,7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [25]:
np.arange(1,13).reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [27]:
# create an arrays of zeros
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
x=np.ones((10,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
print(x.dtype)

float64


In [36]:
np.ones((10,10), dtype="int")

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [37]:
# array of random element
np.random.random(10)

array([0.39774983, 0.6662737 , 0.5129584 , 0.77355553, 0.42300824,
       0.13895593, 0.60730374, 0.77692517, 0.02514931, 0.05355186])

In [47]:
np.random.seed(3)

In [48]:
np.random.random((10,5))

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695],
       [0.89629309, 0.12558531, 0.20724288, 0.0514672 , 0.44080984],
       [0.02987621, 0.45683322, 0.64914405, 0.27848728, 0.6762549 ],
       [0.59086282, 0.02398188, 0.55885409, 0.25925245, 0.4151012 ],
       [0.28352508, 0.69313792, 0.44045372, 0.15686774, 0.54464902],
       [0.78031476, 0.30636353, 0.22195788, 0.38797126, 0.93638365],
       [0.97599542, 0.67238368, 0.90283411, 0.84575087, 0.37799404],
       [0.09221701, 0.6534109 , 0.55784076, 0.36156476, 0.2250545 ],
       [0.40651992, 0.46894025, 0.26923558, 0.29179277, 0.4576864 ],
       [0.86053391, 0.5862529 , 0.28348786, 0.27797751, 0.45462208]])

In [56]:
np.random.randint(5,10,(5,10))

array([[8, 7, 9, 8, 6, 8, 5, 8, 5, 9],
       [7, 6, 7, 8, 7, 7, 9, 6, 9, 7],
       [6, 8, 6, 7, 7, 8, 6, 9, 7, 7],
       [9, 9, 6, 8, 7, 9, 6, 7, 9, 9],
       [5, 8, 6, 7, 6, 8, 8, 8, 7, 6]])